class Autogenerated {
  String? username;
  String? gender;
  String? phone;
  String? date;

  Autogenerated({this.username, this.gender, this.phone, this.date});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    username = json['Username'];
    gender = json['Gender'];
    phone = json['Phone'];
    date = json['Date'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['Username'] = this.username;
    data['Gender'] = this.gender;
    data['Phone'] = this.phone;
    data['Date'] = this.date;
    return data;
  }
}
